// data.js
// contains the data about ever one involve in the production
export interface Person {
  first: string;
  last: string;
  role: string;
  crew: string;
  billingPriority: number;
  bio: string;
  photoPath: string;
  whatTheyDo: string;
}

export const peopleData = [
    {
      first: "Ryker",
      last: "D’Angelo",
      role: "cast",
      crew: "cast",
      billingPriority: 1,
      bio: "Gail Gonzalez [they/them] (Guide) is a 3rd-year SOIS student with dual concentrations in Psychology and ASL Interpreting. They are in the second cohort of the ASLIE’s Certificate in Deaf Interpreting program. An avid participant of RIT & NTID Performing Arts, you may have seen them before as Death in Everybody or as O.G. Howland in Men on Boats. They would like to express gratitude and appreciation to their loved ones (you know who you are :D). Enjoy the show!",
      photoPath: "headshots/GailG.jpg",
      whatTheyDo: "Guide",
    },
    {
      first: "Jaide",
      last: "Winant",
      role: "cast",
      crew: "cast",
      billingPriority: 1,
      bio: "Jaide Winant [she/her] (Ophelia) is a 4th-year ASL Interpreting major from Albany, NY. She has had the wonderful opportunity of being involved in two previous productions with RIT & NTID Performing Arts where she played Daniela in In The Heights and Galya Armolinskaya in Deaf Republic. She’d like to thank the cast and crew for their dedication and hard work over the last few months to put together this unique production. Break a leg/finger!",
      photoPath: "headshots/JaideW.jpg",
      whatTheyDo: "Ophelia",
    },
    {
      first: "Valentina",
      last: "Camino",
      role: "cast",
      crew: "cast",
      billingPriority: 2,
      bio: "Valentina Camino [she/her] (Laertes) is a transfer 1st-year student majoring in Liberal Arts–Journalism. She is from Kenosha, WI. Valentina’s favorite role was playing the mother of Veruca Salt in Charlie and the Chocolate Factory. Though her role is a minor character, she is still shining brightly. She’d like to thank everybody! Mwah gorgeous.",
      photoPath: "headshots/ValentinaC.jpg",
      whatTheyDo: "Laertes",
    },
    {
      first: "Elliana",
      last: "Soto",
      role: "cast",
      crew: "cast",
      billingPriority: 2,
      bio: "Elliana Soto [she/her] (Polonius) is a 4th-year ASL Interpreting major. Born and raised in Rochester, NY, her favorite role was in high school when she played Marci in Almost, Maine. Elliana would like to thank all of the cast and crew for such an amazing experience.",
      photoPath: "headshots/EllianaS.jpg",
      whatTheyDo: "Polonius",
    },
    {
      first: "Lavada",
      last: "Holz",
      role: "cast",
      crew: "cast",
      bio: "Lavada Holz [they/them] (Hamlet) is a 2nd-year ASL Interpreting major from Sultan, WA. If this play was on a stage, it would be their first onstage role since high school! They love working with their castmates, like they did as a swing for the RIT & NTID Performing Arts production of Everybody. They have also appeared in Tracks! and Oh, What a Tangled Web! They hope that whichever cast of characters you see, you’ll love this one-of-a-kind performance. Enjoy!",
      billingPriority: 2,
      photoPath: "headshots/LavadaH.jpg",
      whatTheyDo: "Hamlet",
    },
    {
      first: "Sofia",
      last: "DeCredico",
      role: "cast",
      crew: "cast",
      bio: "Sofia DeCredico [she/her] (Guide) is in her last year in the Applied and Computational Mathematics BS/MS program. Some of Sofia’s favorite roles include dancing in a production of Spoon River Anthology and playing Bradley in Men on Boats. Sofia would like to thank the entire cast and crew for working so hard to put this unique show together. Hope you enjoy!",
      billingPriority: 2,
      photoPath: "headshots/SofiaD.jpg",
      whatTheyDo: "Guide",
    },
    {
      first: "Rebecca",
      last: "Lewis",
      role: "cast",
      crew: "cast",
      bio: "Rebecca Lewis [she/they] (Ophelia) is a 2nd-year Medical Illustration major from Colorado Springs, CO. Before this show you may have seen her on campus as the Lottery Roles in Everybody and Vera Claythorne in And Then There Were None. She would like you to know that her cat’s name is in fact Ophelia, but she could not be here tonight. Enjoy our take on Shakespeare’s Hamlet!",
      billingPriority: 2,
      photoPath: "headshots/RebeccaL.jpg",
      whatTheyDo: "Ophelia",
    },
    {
      first: "Nathalie",
      last: "Phongsavanh",
      role: "cast",
      crew: "cast",
      bio: "Nathalie Phongsavanh [she/her] (Laertes) is a 1st-year student currently majoring in Science Exploration. Coming from an international background, some of Nathalie’s favorite roles include The Lion from The Wizard of Oz and The Cheshire Cat from Alice Through The Looking Glass–like the charismatic cool cat she is. She would like to thank the cast, crew, and audience members. Please please please enjoy the show!",
      billingPriority: 2,
      photoPath: "headshots/NathalieP.jpg",
      whatTheyDo: "Laertes",
    },
    {
      first: "Bruno",
      last: "Karpinski",
      role: "cast",
      crew: "cast",
      bio: "Bruno Karpinksi (Polonius) is a 1st-year Mechanical Engineering major from Bowie, MD. His favorite role is that of Colonel Mustard from his high school’s production of Clue. He hopes you enjoy this unique theater experience.",
      billingPriority: 2,
      photoPath: "headshots/BrunoK.jpg",
      whatTheyDo: "Polonius",
    },
    {
      first: "Teddy",
      last: "Walsh",
      role: "cast",
      crew: "cast",
      bio: "Teddy Walsh [he/him] (Hamlet) is a 4th-year Game Design and Development major. He’s from Newton, MA. Last year he played Evil Soldier #2 and the voice of several villagers in Deaf Republic! He won’t tell you to enjoy the show because it's a free country and you can do what you want.",
      billingPriority: 2,
      photoPath: "headshots/TeddyW.jpg",
      whatTheyDo: "Hamlet",
    },
    {
      first: "Abby",
      last: "Hill",
      role: "cast",
      crew: "cast",
      bio: "Abby Hill (Guide) is a 4th-year ASL Interpreting major and originally from Dallas, TX. Some of her favorite roles include John Wesley Powell in Men on Boats, Guardian Angel in Angels in America: Millennium Approaches, and Gwendolyn Fairfax in The Importance of Being Earnest. She is so excited to be a part of such a unique show and can’t thank the cast and crew enough for being so lovely. ",
      billingPriority: 3,
      photoPath: "headshots/AbbyH.jpg",
      whatTheyDo: "Guide",
    },
    {
      first: "Ace",
      last: "Gray",
      role: "cast",
      crew: "cast",
      bio: "Ace Gray [they/them] (Ophelia) is a 4th-year English major from Silver Spring, MD. You may have seen them as Everybody and Evil in the RIT & NTID Performing Arts production of Everybody. They would like to thank all of their loved ones for supporting them throughout this production. Enjoy the show! \(｡^‿^｡)/",
      billingPriority: 3,
      photoPath: "headshots/AceG.jpg",
      whatTheyDo: "Ophelia",
    },
    {
      first: "Alaina",
      last: "Biddle",
      role: "cast",
      crew: "cast",
      bio: "Alaina Biddle (Laertes) is a 3rd-year ASL Interpreting major from Hanover, PA. Alaina has previously been heavily involved with RIT Players and is excited to be in her first RIT & NTID Performing Arts show! Enjoy!",
      billingPriority: 3,
      photoPath: "headshots/AlainaB.jpg",
      whatTheyDo: "Laertes",
    },
    {
      first: "Raihiem",
      last: "Marshall",
      role: "cast",
      crew: "cast",
      bio: "Raihiem Marshall (Polonius) is a 4th-year student in the School of Individualized Study with a concentration in Leadership and Management and a minor in Theatre Arts. His favorite role is Lysander from Shakespeare’s A Midsummer Night’s Dream. He has also performed for RIT & NTID Performing Arts in Taming of the Shrew, Angels in America: Millennium Approaches, Everybody, and Deaf Republic. He loves acting and playing video games. ",
      billingPriority: 3,
      photoPath: "headshots/RaihiemM.jpg",
      whatTheyDo: "Polonius",
    },
    {
      first: "Tayori",
      last: "Snipe",
      role: "cast",
      crew: "cast",
      bio: "Tayori Snipe [he/him] (Hamlet) is a 1st-year student majoring in ASL Interpreting. Tayori is from Loudoun County, VA. Tayori’s favorite role has been playing Scarecrow in The Wizard of Oz. Hope you enjoy the show!",
      billingPriority: 3,
      photoPath: "headshots/TayoriS.jpg",
      whatTheyDo: "Hamlet",
    },
    {
      first: "Benson",
      last: "Haley",
      role: "cast",
      crew: "cast",
      bio: "Benson Haley [he/him] (Guide) is a 3rd-year Computer Science major at RIT, and he is elated to be working with the cast of Thy Name is Woman. In years prior, he has procrastinated his classwork by playing Justice Wargrave in the RIT Players production of And Then There Were None as well as the Voice of Louis in the RIT & NTID Performing Arts production of Angels in America: Millennium Approaches. Benson blames his family, friends, and the Columbia Players for giving him the support that allowed him to end up in this production.",
      billingPriority: 4,
      photoPath: "headshots/BensonH.jpg",
      whatTheyDo: "Guide",
    },
    {
      first: "Alyssa",
      last: "Rzasa",
      role: "cast",
      crew: "cast",
      bio: "Alyssa Rzasa [she/her] (Ophelia) is a 2nd-year Biomedical Engineering student from New Hampshire. Some of her favorite roles include Berthe in Pippin and Megan in Puffs. She would like to thank the production team, cast, and crew for an amazing show! Have a wicked fun time!",
      billingPriority: 4,
      photoPath: "headshots/AlyssaR.jpg",
      whatTheyDo: "Ophelia",
    },
    {
      first: "Damien ",
      last: "Sorvillo",
      role: "cast",
      crew: "cast",
      bio: "Damien Sorvillo [they/them] (Laertes) is a 1st-year Animation major. They are from the small town of Portville, NY. Some of their previous roles include Mr. Turlly in A Christmas Carol, Cogsworth in Beauty and the Beast, Banzai in The Lion King, and Mal in The Addams Family.",
      billingPriority: 4,
      photoPath: "headshots/DamienS.jpg",
      whatTheyDo: "Laertes",
    },
    {
      first: "Pierre-Ilias",
      last: "Arzimanoglou",
      role: "cast",
      crew: "cast",
      bio: "Pierre-Ilias Arzimanoglou [he/him] (Polonius) is a 1st-year 3D Digital Design student. Coming from France, he is very excited for his first production in the USA! He has not acted in the past four years but is very excited to get back at it! He would like to thank his family for supporting him despite the distance, and thank the cast and crew for allowing him to participate in such a cool production! Profitez bien du spectacle! Bisous!",
      billingPriority: 4,
      photoPath: "headshots/PierreA.jpg",
      whatTheyDo: "Polonius",
    },
    {
      first: "Skyler",
      last: "Herman",
      role: "cast",
      crew: "cast",
      bio: "Skyler Herman [he/him] (Hamlet) is a 5th-year Software Engineering major from Montville, NJ. You may have seen him as Chuck in the RIT & NTID Performing Arts production of She Kills Monsters: Virtual Realms. Skyler is an active member of RIT Players and the Rocky Horror Club on campus. He would like to thank his friends and family for their constant support, as well as the production team for giving him the opportunity to make theatre in his last year here at RIT.",
      billingPriority: 4,
      photoPath: "headshots/SkylerH.jpg",
      whatTheyDo: "Hamlet",
    },
    {
      first: "tech",
      last: "guy",
      role: "crew",
      crew: "crew",
      bio: "does stuff",
      billingPriority: 5,
      photoPath: "headshots/headshot-placeholder.png",
      whatTheyDo: "Guide",
    }
  ];
  